get메소드를 entity로 리턴을 했습니다
- 발생한 오류 입니다
2023-05-01 16:59:43 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.ClassCastException: class com.agile.demo.biz.account.AccountEntity cannot be cast to class java.io.Serializable (com.agile.demo.biz.account.AccountEntity is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @54cf206a; java.io.Serializable is in module java.base of loader 'bootstrap')] with root cause
java.lang.ClassCastException: class com.agile.demo.biz.account.AccountEntity cannot be cast to class java.io.Serializable (com.agile.demo.biz.account.AccountEntity is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @54cf206a; java.io.Serializable is in module java.base of loader 'bootstrap')